### PR TITLE
Fixed stretched out image

### PR DESCRIPTION
**Pull request by LukaHietala**
A really small fix that I'd like to fix because it is bugging me

Before:

Screenshot from 2023-01-16 17-57-18

After:

Screenshot from 2023-01-16 18-07-07

### CODE REVIEW

**Comment by juliusmarminge** [comment]
This is weird, the image is in aspect 2:1 so applying `aspect-[2/1]` should be correct no?

**Comment by LukaHietala** [comment]
With just the `aspect-[2/1]` it looks stretched out

**Comment by LukaHietala** [comment]
I tried to find many ways to fit the image to that div, but `object-cover` was the only thing that worked... Kind of

**Comment by juliusmarminge** [comment]
alright thanks...

might check what's up later cause that image should be 2:1...

**Pull request merged**
